services:
  postgres:
    image: postgres:16-alpine
    container_name: ccarre_postgres
    restart: always
    environment:
      POSTGRES_DB: ccarre_db
      POSTGRES_USER: ccarre_user
      POSTGRES_PASSWORD: SuperStrongPassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
